# WARNING - Generated by {fusen} from dev/flat_crystallography.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Specific extractors pull correct data", {
  cif_file_path <- system.file("extdata", "ICSD422.cif", package = "crysmal")
  skip_if(nchar(cif_file_path) == 0, "Sample data not found, skipping test.")
  cif_content <- data.table::fread(cif_file_path, sep = "\n", header = FALSE, col.names = "V1")
  
  expect_equal(extract_database_code(cif_content), "ICSD 422")
  expect_equal(extract_chemical_formula(cif_content), "Si1 Sr2")
  expect_equal(extract_space_group_name(cif_content), "P n m a")
  expect_equal(extract_space_group_number(cif_content), "62")
})
