# WARNING - Generated by {fusen} from dev/flat_crystallography.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Main processing pipeline runs correctly", {
  cif_file_path <- system.file("extdata", "ICSD422.cif", package = "crysmal")
  skip_if(nchar(cif_file_path) == 0, "Sample data not found, skipping test.")
  
  results <- process_cif_files(c(cif_file_path))
  
  expect_s3_class(results, "data.table")
  expect_equal(nrow(results), 1)
  expect_equal(results$database_code, "ICSD 422")
  expect_s3_class(results$bonded_pairs[], "data.table")
  expect_true("DistanceError" %in% names(results$bonded_pairs[]))
})
