---
title: "Development Actions History"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Project Setup Commands
# Run these commands in the R console ONE TIME to set up the package.

```{r description, eval=FALSE, overwrite=TRUE}
fusen::fill_description(
  pkg = here::here(),
  fields = list(
    Package = "crysmal",
    Title = "Tools to Extract Data from CIF Files for Crystallography",
    Version = "0.1.0",
    `Authors@R` = person(
      "Don", "Ngo", 
      email = "dngo@carnegiescience.edu", 
      role = c("aut", "cre")
    ),
    Description = "Provides a suite of functions to parse Crystallographic Information Files (.cif), extracting essential data such as chemical formulas, unit cell parameters, atomic coordinates, and symmetry operations. It also includes tools to calculate interatomic distances, identify bonded pairs using various algorithms (Minimum Distance, Brunner's, Hoppe's), determine nearest neighbor counts, and calculate bond angles. The package is designed to facilitate the preparation of crystallographic data for further analysis, including machine learning applications in materials science.",
    `Depends` = "R (>= 3.5.0)"
  )
)

# 2. Set the license to GPL-3
usethis::use_gpl3_license()

# 3. Add the pipe operator (%>%) for use throughout the package
usethis::use_pipe()
```

# Manage Dependencies
# Run these commands ONE TIME to list required packages in the DESCRIPTION file.

```{r dependencies, eval=FALSE}
# Add packages to Imports
usethis::use_package("data.table")
usethis::use_package("dplyr")
usethis::use_package("stringr")

# Add packages to Suggests and set up testing infrastructure
usethis::use_testthat() # Adds testthat to Suggests
usethis::use_package("knitr", type = "Suggests")
usethis::use_package("rmarkdown", type = "Suggests")
```

# Inflate the Package
# This is the main command. Run this any time you change the flat file.

```{r inflate, eval=FALSE}
fusen::inflate(
  flat_file = "dev/flat_crystallography.Rmd", 
  vignette_name = "Get Started with crysmal"
)
```

# Ongoing Development Commands
# Use these commands as needed while developing.

```{r development-commands, eval=FALSE}
# Load all your package functions into the console for interactive testing
pkgload::load_all()

# Run a full check on your package (includes tests, documentation, etc.)
devtools::check()

# Install your package locally
devtools::install()
```
