flat_crystallography.Rmd:
  path: dev/flat_crystallography.Rmd
  state: active
  R:
  - R/apply_symmetry_operations.R
  - R/minimum_distance.R
  - R/calculate_distances.R
  - R/extract_unit_cell_metrics.R
  - R/extract-helpers.R
  - R/process_cif_files.R
  - R/propagate_distance_error.R
  tests: tests/testthat/test-process_cif_files.R
  vignettes: vignettes/get-started-with-crysmal.Rmd
  inflate:
    flat_file: dev/flat_crystallography.Rmd
    vignette_name: Get Started with crysmal
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
