# WARNING - Generated by {fusen} from dev/flat_crystallography.Rmd: do not edit by hand # nolint: line_length_linter.

#' Apply Symmetry Operations
#' @description Generates all symmetry-equivalent atomic positions.
#' @param atomic_coordinates A data.table from `extract_atomic_coordinates`.
#' @param symmetry_operations A data.table from `extract_symmetry_operations`.
#' @return A data.table containing all unique atomic positions in the unit cell.
#' @import data.table dplyr
#' @export
apply_symmetry_operations <- function(atomic_coordinates, symmetry_operations) {
  apply_op <- function(op, x, y, z) { op <- gsub("x",sprintf("(%f)",x), op); op <- gsub("y",sprintf("(%f)",y),op); op <- gsub("z",sprintf("(%f)",z),op); eval(parse(text=op)) }
  expand_coords <- function(row, sym_ops) {
    x <- row$x_a; y <- row$y_b; z <- row$z_c
    new_coords <- rbindlist(lapply(1:nrow(sym_ops), function(i) {
      data.table(Label=paste(row$Label,i,sep="_"), x_a=apply_op(sym_ops[i,x],x,y,z)%%1, y_b=apply_op(sym_ops[i,y],x,y,z)%%1, z_c=apply_op(sym_ops[i,z],x,y,z)%%1)
    }))
    return(new_coords)
  }
  transformed_coords <- rbindlist(lapply(1:nrow(atomic_coordinates), function(i) expand_coords(atomic_coordinates[i,], symmetry_operations)))
  return(transformed_coords %>% distinct(x_a, y_b, z_c, .keep_all = TRUE))
}

#' Expand to Neighboring Unit Cells
#' @description Replicates atoms into a 3x3x3 supercell grid.
#' @param transformed_coords A data.table of atom positions within one unit cell.
#' @return A data.table containing all atomic positions in the expanded supercell.
#' @import data.table dplyr
#' @export
expand_transformed_coords <- function(transformed_coords) {
  cell_indices <- as.data.table(expand.grid(x=-1:1, y=-1:1, z=-1:1))
  expanded_coords <- rbindlist(lapply(1:nrow(cell_indices), function(i) {
    shift <- cell_indices[i,]; transformed_coords[,.(Label=paste(Label,paste(shift$x,shift$y,shift$z,sep="_"),sep="_"), x_a=x_a+shift$x, y_b=y_b+shift$y, z_c=z_c+shift$z)]
  }))
  return(expanded_coords %>% distinct(x_a, y_b, z_c, .keep_all = TRUE))
}
