# WARNING - Generated by {fusen} from dev/flat_crystallography.Rmd: do not edit by hand # nolint: line_length_linter.

#' Calculate Neighbor Counts
#' @description Counts nearest neighbors for each central atom.
#' @param bonded_pairs_table A data.table of bonded pairs.
#' @return A data.table with columns 'Atom' and 'NeighborCount'.
#' @import data.table
#' @export
calculate_neighbor_counts <- function(bonded_pairs_table) {
  if (is.null(bonded_pairs_table) || nrow(bonded_pairs_table) == 0) {
    return(data.table(Atom = character(), NeighborCount = integer()))
  }
  neighbor_counts <- bonded_pairs_table[, .(NeighborCount = .N), by = .(Atom1)]
  setnames(neighbor_counts, "Atom1", "Atom")
  return(neighbor_counts)
}

#' Calculate Bond Angles
#' @description Calculates all bond angles centered on each atom.
#' @param bonded_pairs Data.table of bonded atoms.
#' @param atomic_coordinates Data.table of asymmetric atom coordinates.
#' @param expanded_coords Data.table of supercell atom coordinates.
#' @param unit_cell_metrics Data.table with unit cell parameters.
#' @return A data.table of all unique bond angles.
#' @import data.table utils
#' @export
calculate_angles <- function(bonded_pairs, atomic_coordinates, expanded_coords, unit_cell_metrics) {
  a<-unit_cell_metrics$`_cell_length_a`; b<-unit_cell_metrics$`_cell_length_b`; c<-unit_cell_metrics$`_cell_length_c`
  alpha_rad<-unit_cell_metrics$`_cell_angle_alpha`*pi/180; beta_rad<-unit_cell_metrics$`_cell_angle_beta`*pi/180; gamma_rad<-unit_cell_metrics$`_cell_angle_gamma`*pi/180
  cos_alpha<-cos(alpha_rad); cos_beta<-cos(beta_rad); cos_gamma<-cos(gamma_rad)
  all_coords <- unique(rbind(atomic_coordinates[,.(Label,x_a,y_b,z_c)], expanded_coords[,.(Label,x_a,y_b,z_c)]), by="Label"); setkey(all_coords, Label)
  
  calculate_angle_metric <- function(c_atom, n1_atom, n2_atom) {
    coord1<-all_coords[c_atom,.(x_a,y_b,z_c)]; coord2<-all_coords[n1_atom,.(x_a,y_b,z_c)]; coord3<-all_coords[n2_atom,.(x_a,y_b,z_c)]
    if(anyNA(coord1)|anyNA(coord2)|anyNA(coord3)) return(NA_real_)
    v1_frac<-as.numeric(coord2-coord1); v2_frac<-as.numeric(coord3-coord1)
    xf1<-v1_frac;yf1<-v1_frac;zf1<-v1_frac; xf2<-v2_frac;yf2<-v2_frac;zf2<-v2_frac
    dot_prod<-(xf1*xf2*a^2+yf1*yf2*b^2+zf1*zf2*c^2+(xf1*yf2+yf1*xf2)*a*b*cos_gamma+(xf1*zf2+zf1*xf2)*a*c*cos_beta+(yf1*zf2+zf1*yf2)*b*c*cos_alpha)
    mag_sq1<-(xf1^2*a^2+yf1^2*b^2+zf1^2*c^2+2*xf1*yf1*a*b*cos_gamma+2*xf1*zf1*a*c*cos_beta+2*yf1*zf1*b*c*cos_alpha)
    mag_sq2<-(xf2^2*a^2+yf2^2*b^2+zf2^2*c^2+2*xf2*yf2*a*b*cos_gamma+2*xf2*zf2*a*c*cos_beta+2*yf2*zf2*b*c*cos_alpha)
    if (mag_sq1<=1e-10||mag_sq2<=1e-10) return(NA_real_)
    cos_theta <- min(max(dot_prod/(sqrt(mag_sq1)*sqrt(mag_sq2)),-1.0),1.0)
    return(acos(cos_theta)*180/pi)
  }
  
  angle_list <- list()
  unique_central_atoms <- unique(bonded_pairs$Atom1)
  for (central_atom in unique_central_atoms) {
    bonded_neighbors <- bonded_pairs[Atom1==central_atom, Atom2]
    if (length(bonded_neighbors) >= 2) {
      neighbor_combinations <- combn(bonded_neighbors, 2, simplify=FALSE)
      for (pair in neighbor_combinations) {
        # FIX: Correctly call the calculation and store the results
        angle <- calculate_angle_metric(central_atom, pair, pair)
        if (!is.na(angle)) {
          angle_list[[length(angle_list)+1]] <- data.table(CentralAtom=central_atom, Neighbor1=pair, Neighbor2=pair, Angle=angle)
        }
      }
    }
  }
  
  if (length(angle_list)>0) { return(rbindlist(angle_list)[order(CentralAtom, Neighbor1, Neighbor2)]) } else {
    return(data.table(CentralAtom=character(),Neighbor1=character(),Neighbor2=character(),Angle=numeric()))
  }
}
