# WARNING - Generated by {fusen} from dev/flat_crystallography.Rmd: do not edit by hand # nolint: line_length_linter.

#' Extract Metadata from CIF Content
#' 
#' @description A group of functions to extract specific metadata tags from CIF file content.
#' `extract_value` is the internal helper function, while the others are exported for direct use.
#' 
#' @param cif_content A data.table where each row is a line from the CIF file.
#' @param pattern The text pattern (e.g., "_database_code_") to search for.
#' @param remove_pattern A boolean indicating whether to remove the search pattern.
#'
#' @return A character string of the cleaned value, or NA if not found.
#' @name extract-helpers
NULL

#' @rdname extract-helpers
#' @keywords internal
#' @noRd
extract_value <- function(cif_content, pattern, remove_pattern = TRUE) {
  lines <- cif_content[V1 %like% pattern]
  if (nrow(lines) > 0) {
    value <- lines$V1
    if (remove_pattern) { value <- gsub(pattern, "", value) }
    value <- gsub("'", "", value); value <- trimws(value)
    return(value)
  } else { return(NA) }
}

#' @rdname extract-helpers
#' @export
extract_database_code <- function (cif_content) { extract_value(cif_content, "_database_code_") }
#' @rdname extract-helpers
#' @export
extract_chemical_formula <- function(cif_content) { extract_value(cif_content, "_chemical_formula_sum") }
#' @rdname extract-helpers
#' @export
extract_structure_type <- function(cif_content) { extract_value(cif_content, "_chemical_name_structure_type") }
#' @rdname extract-helpers
#' @export
extract_space_group_name <- function(cif_content) { extract_value(cif_content, "_space_group_name_H-M_alt") }
#' @rdname extract-helpers
#' @export
extract_space_group_number <- function(cif_content) { extract_value(cif_content, "_space_group_IT_number") }
