# WARNING - Generated by {fusen} from dev/flat_crystallography.Rmd: do not edit by hand # nolint: line_length_linter.

#' Extract values from CIF content
#' @description A group of functions to extract specific metadata from CIF file content.
#' `extract_value` is the internal helper function. The others are exported.
#' @param cif_content A data.table where each row is a line from the CIF file.
#' @param pattern The text pattern (e.g., "_database_code_") to search for.
#' @param remove_pattern A boolean indicating whether to remove the search pattern from the result.
#' @return A character string of the cleaned value, or NA if not found.
#' @noRd
#' @examples
#' cif_file_path <- system.file("extdata", "ICSD422.cif", package = "crysmal")
#' if(nchar(cif_file_path) > 0) {
#'   cif_content <- data.table::fread(cif_file_path, sep = "\n", header = FALSE, col.names = "V1")
#'   print(extract_database_code(cif_content))
#'   print(extract_chemical_formula(cif_content))
#' }
extract_value <- function(cif_content, pattern, remove_pattern = TRUE) {
  lines <- cif_content[V1 %like% pattern]
  if (nrow(lines) > 0) {
    value <- lines$V1 # Take the first line if multiple matches
    if (remove_pattern) { value <- gsub(pattern, "", value) }
    value <- gsub("'", "", value); value <- trimws(value)
    return(value)
  } else { return(NA) }
}

#' @describeIn extract_value Extract Database Code
#' @export
extract_database_code <- function (cif_content) { extract_value(cif_content, "_database_code_") }
#' @describeIn extract_value Extract Chemical Formula
#' @export
extract_chemical_formula <- function(cif_content) { extract_value(cif_content, "_chemical_formula_sum") }
#' @describeIn extract_value Extract Structure Type
#' @export
extract_structure_type <- function(cif_content) { extract_value(cif_content, "_chemical_name_structure_type") }
#' @describeIn extract_value Extract Space Group Name
#' @export
extract_space_group_name <- function(cif_content) { extract_value(cif_content, "_space_group_name_H-M_alt") }
#' @describeIn extract_value Extract Space Group Number
#' @export
extract_space_group_number <- function(cif_content) { extract_value(cif_content, "_space_group_IT_number") }
