# WARNING - Generated by {fusen} from dev/flat_crystallography.Rmd: do not edit by hand # nolint: line_length_linter.

#' Process a List of CIF Files
#' @description The main wrapper function that iterates through CIF files,
#' applies all analysis steps, and compiles the results.
#' @param cif_list A character vector of paths to CIF files.
#' @return A single data.table where each row represents one processed CIF file.
#' @import data.table
#' @export
#' @examples
#' cif_file_path <- system.file("extdata", "ICSD422.cif", package = "crysmal")
#' if(nchar(cif_file_path) > 0) {
#'   all_data <- process_cif_files(cif_list = c(cif_file_path))
#'   print(all_data)
#' }
process_cif_files <- function(cif_list) {
  # FIX: Removed the unused `warn = FALSE` argument from the fread call.
  cif_tab_list <- lapply(cif_list, fread, sep = "\n", header = FALSE, col.names = "V1")
  
  results_list <- list()
  for (i in seq_along(cif_tab_list)) {
    cif <- cif_tab_list[[i]]; cif_path <- cif_list[i]
    result <- tryCatch({
      database_code<-extract_database_code(cif); chemical_formula<-extract_chemical_formula(cif)
      unit_cell_metrics<-extract_unit_cell_metrics(cif); atomic_coordinates<-extract_atomic_coordinates(cif); symmetry_operations<-extract_symmetry_operations(cif)
      if(is.null(atomic_coordinates)||is.null(symmetry_operations)||is.null(unit_cell_metrics)||nrow(atomic_coordinates)==0) stop("Essential data missing.")
      transformed_coords<-apply_symmetry_operations(atomic_coordinates,symmetry_operations); expanded_coords<-expand_transformed_coords(transformed_coords)
      distances<-calculate_distances(atomic_coordinates,expanded_coords,unit_cell_metrics); bonded_pairs<-minimum_distance(distances)
      neighbor_counts<-calculate_neighbor_counts(bonded_pairs); bond_angles<-calculate_angles(bonded_pairs,atomic_coordinates,expanded_coords,unit_cell_metrics)
      brunner_pairs <- brunner(distances); hoppe_pairs <- hoppe(distances)
      bonded_pairs_with_error<-propagate_distance_error(bonded_pairs,atomic_coordinates,unit_cell_metrics); bond_angles_with_error<-propagate_angle_error(bond_angles,atomic_coordinates,expanded_coords,unit_cell_metrics)
      
      data.table(
        file_path = cif_path,
        database_code = database_code,
        chemical_formula = chemical_formula,
        unit_cell_metrics = list(unit_cell_metrics),
        atomic_coordinates = list(atomic_coordinates),
        symmetry_operations = list(symmetry_operations),
        transformed_coords = list(transformed_coords),
        expanded_coords = list(expanded_coords),
        distances = list(distances),
        bonded_pairs = list(bonded_pairs_with_error),
        brunner_pairs = list(brunner_pairs),
        hoppe_pairs = list(hoppe_pairs),
        neighbor_counts = list(neighbor_counts),
        bond_angles = list(bond_angles_with_error)
      )
    }, error = function(e) {
      warning(paste("Failed to process file:", cif_path, "\nError:", e$message)); return(NULL)
    })
    results_list[[i]] <- result
  }
  return(rbindlist(results_list, fill = TRUE))
}
