# WARNING - Generated by {fusen} from dev/flat_crystallography.Rmd: do not edit by hand # nolint: line_length_linter.

#' Propagate Distance Error
#' @description Calculates the standard uncertainty for each interatomic distance.
#' @param bonded_pairs Data.table of bonded atoms with their distances.
#' @param atomic_coordinates Data.table with fractional coordinates and errors.
#' @param unit_cell_metrics Data.table with unit cell parameters and errors.
#' @return The input `bonded_pairs` data.table with a new 'DistanceError' column.
#' @import data.table
#' @export
propagate_distance_error <- function(bonded_pairs, atomic_coordinates, unit_cell_metrics) {
  if (is.null(bonded_pairs) || nrow(bonded_pairs) == 0) { if(!is.null(bonded_pairs)) bonded_pairs[, DistanceError := NA_real_]; return(bonded_pairs) }
  a<-unit_cell_metrics$`_cell_length_a`;s_a<-unit_cell_metrics$`_cell_length_a_error`;b<-unit_cell_metrics$`_cell_length_b`;s_b<-unit_cell_metrics$`_cell_length_b_error`;c<-unit_cell_metrics$`_cell_length_c`;s_c<-unit_cell_metrics$`_cell_length_c_error`
  alpha_rad<-unit_cell_metrics$`_cell_angle_alpha`*pi/180;s_alpha_rad<-unit_cell_metrics$`_cell_angle_alpha_error`*pi/180;beta_rad<-unit_cell_metrics$`_cell_angle_beta`*pi/180;s_beta_rad<-unit_cell_metrics$`_cell_angle_beta_error`*pi/180;gamma_rad<-unit_cell_metrics$`_cell_angle_gamma`*pi/180;s_gamma_rad<-unit_cell_metrics$`_cell_angle_gamma_error`*pi/180
  cos_a<-cos(alpha_rad);sin_a<-sin(alpha_rad);cos_b<-cos(beta_rad);sin_b<-sin(beta_rad);cos_g<-cos(gamma_rad);sin_g<-sin(gamma_rad)
  s_a<-ifelse(is.na(s_a),0,s_a);s_b<-ifelse(is.na(s_b),0,s_b);s_c<-ifelse(is.na(s_c),0,s_c);s_alpha_rad<-ifelse(is.na(s_alpha_rad),0,s_alpha_rad);s_beta_rad<-ifelse(is.na(s_beta_rad),0,s_beta_rad);s_gamma_rad<-ifelse(is.na(s_gamma_rad),0,s_gamma_rad)
  work_dt<-copy(bonded_pairs);setnames(work_dt,c("DeltaX","DeltaY","DeltaZ"),c("dx","dy","dz"));atom_errors<-atomic_coordinates[,.(Label,s_xf=x_error,s_yf=y_error,s_zf=z_error)]
  work_dt<-merge(work_dt,atom_errors,by.x="Atom1",by.y="Label",all.x=TRUE);setnames(work_dt,c("s_xf","s_yf","s_zf"),c("s_xf1","s_yf1","s_zf1"));work_dt[,Original_Atom2:=sub("_.*","",Atom2)];work_dt<-merge(work_dt,atom_errors,by.x="Original_Atom2",by.y="Label",all.x=TRUE);setnames(work_dt,c("s_xf","s_yf","s_zf"),c("s_xf2","s_yf2","s_zf2"));work_dt[,Original_Atom2:=NULL]
  coord_err_cols<-c("s_xf1","s_yf1","s_zf1","s_xf2","s_yf2","s_zf2");for(col in coord_err_cols)set(work_dt,which(is.na(work_dt[[col]])),col,0)
  work_dt[,term_common:=1/(2*Distance)];work_dt[,pd_a:=term_common*(2*a*dx^2+2*b*dx*dy*cos_g+2*c*dx*dz*cos_b)];work_dt[,pd_b:=term_common*(2*b*dy^2+2*a*dx*dy*cos_g+2*c*dy*dz*cos_a)];work_dt[,pd_c:=term_common*(2*c*dz^2+2*a*dx*dz*cos_b+2*b*dy*dz*cos_a)];work_dt[,pd_alpha:=term_common*(-2*b*c*dy*dz*sin_a)];work_dt[,pd_beta:=term_common*(-2*a*c*dx*dz*sin_b)];work_dt[,pd_gamma:=term_common*(-2*a*b*dx*dy*sin_g)]
  work_dt[,pd_xf1:=term_common*(2*a^2*dx+2*a*b*dy*cos_g+2*a*c*dz*cos_b)];work_dt[,pd_yf1:=term_common*(2*b^2*dy+2*a*b*dx*cos_g+2*b*c*dz*cos_a)];work_dt[,pd_zf1:=term_common*(2*c^2*dz+2*a*c*dx*cos_b+2*b*c*dy*cos_a)];work_dt[,`:=`(pd_xf2=-pd_xf1,pd_yf2=-pd_yf1,pd_zf2=-pd_zf1)]
  work_dt[,variance:=(pd_a*s_a)^2+(pd_b*s_b)^2+(pd_c*s_c)^2+(pd_alpha*s_alpha_rad)^2+(pd_beta*s_beta_rad)^2+(pd_gamma*s_gamma_rad)^2+(pd_xf1*s_xf1)^2+(pd_yf1*s_yf1)^2+(pd_zf1*s_zf1)^2+(pd_xf2*s_xf2)^2+(pd_yf2*s_yf2)^2+(pd_zf2*s_zf2)^2];work_dt[,DistanceError:=sqrt(variance)]
  return(merge(bonded_pairs,work_dt[,.(Atom1,Atom2,Distance,DistanceError)],by=c("Atom1","Atom2","Distance"),all.x=TRUE))
}

#' Propagate Angle Error
#' @description Calculates the standard uncertainty for each bond angle.
#' @param bond_angles Data.table of calculated bond angles.
#' @param atomic_coordinates Data.table with fractional coordinates and errors.
#' @param expanded_coords Data.table of supercell atom coordinates.
#' @param unit_cell_metrics Data.table with unit cell parameters and errors.
#' @return The input `bond_angles` data.table with a new 'AngleError' column.
#' @import data.table
#' @export
propagate_angle_error <- function(bond_angles, atomic_coordinates, expanded_coords, unit_cell_metrics) {
  if(is.null(bond_angles)||nrow(bond_angles)==0){if(!is.null(bond_angles))bond_angles[,AngleError:=NA_real_];return(bond_angles)}
  a<-unit_cell_metrics$`_cell_length_a`;b<-unit_cell_metrics$`_cell_length_b`;c<-unit_cell_metrics$`_cell_length_c`;s_a<-ifelse(is.na(unit_cell_metrics$`_cell_length_a_error`),0,unit_cell_metrics$`_cell_length_a_error`);s_b<-ifelse(is.na(unit_cell_metrics$`_cell_length_b_error`),0,unit_cell_metrics$`_cell_length_b_error`);s_c<-ifelse(is.na(unit_cell_metrics$`_cell_length_c_error`),0,unit_cell_metrics$`_cell_length_c_error`);alpha_rad<-unit_cell_metrics$`_cell_angle_alpha`*pi/180;beta_rad<-unit_cell_metrics$`_cell_angle_beta`*pi/180;gamma_rad<-unit_cell_metrics$`_cell_angle_gamma`*pi/180;s_alpha_rad<-ifelse(is.na(unit_cell_metrics$`_cell_angle_alpha_error`),0,unit_cell_metrics$`_cell_angle_alpha_error`*pi/180);s_beta_rad<-ifelse(is.na(unit_cell_metrics$`_cell_angle_beta_error`),0,unit_cell_metrics$`_cell_angle_beta_error`*pi/180);s_gamma_rad<-ifelse(is.na(unit_cell_metrics$`_cell_angle_gamma_error`),0,unit_cell_metrics$`_cell_angle_gamma_error`*pi/180)
  cos_a<-cos(alpha_rad);sin_a<-sin(alpha_rad);cos_b<-cos(beta_rad);sin_b<-sin(beta_rad);cos_g<-cos(gamma_rad);sin_g<-sin(gamma_rad);v_sq<-1-cos_a^2-cos_b^2-cos_g^2+2*cos_a*cos_b*cos_g;v<-sqrt(v_sq)
  cart_errors<-copy(atomic_coordinates);for(col in c("x_error","y_error","z_error"))set(cart_errors,which(is.na(cart_errors[[col]])),col,0)
  cart_errors[,`:=`(p_xc_a=x_a,p_xc_b=y_b*cos_g,p_xc_c=z_c*cos_b,p_xc_alpha=0,p_xc_beta=-c*z_c*sin_b,p_xc_gamma=-b*y_b*sin_g,p_xc_xf=a,p_xc_yf=b*cos_g,p_xc_zf=c*cos_b,p_yc_a=0,p_yc_b=y_b*sin_g,p_yc_c=z_c*(cos_a-cos_b*cos_g)/sin_g,p_yc_alpha=-c*z_c*sin_a/sin_g,p_yc_beta=c*z_c*sin_b*cos_g/sin_g,p_yc_gamma=b*y_b*cos_g+c*z_c*(cos_b-cos_a*cos_g)/sin_g^2,p_yc_xf=0,p_yc_yf=b*sin_g,p_yc_zf=c*(cos_a-cos_b*cos_g)/sin_g,p_zc_a=0,p_zc_b=0,p_zc_c=z_c*v/sin_g,p_zc_alpha=c*z_c*(cos_b*cos_g-cos_a)/(sin_g*v),p_zc_beta=c*z_c*(cos_a*cos_g-cos_b)/(sin_g*v),p_zc_gamma=-c*z_c*(v_sq*cos_g+sin_g^2*(cos_a*cos_b-cos_g))/(sin_g^2*v),p_zc_xf=0,p_zc_yf=0,p_zc_zf=c*v/sin_g)]
  cart_errors[,s_xc_sq:=(p_xc_a*s_a)^2+(p_xc_b*s_b)^2+(p_xc_c*s_c)^2+(p_xc_alpha*s_alpha_rad)^2+(p_xc_beta*s_beta_rad)^2+(p_xc_gamma*s_gamma_rad)^2+(p_xc_xf*x_error)^2+(p_xc_yf*y_error)^2+(p_xc_zf*z_error)^2];cart_errors[,s_yc_sq:=(p_yc_a*s_a)^2+(p_yc_b*s_b)^2+(p_yc_c*s_c)^2+(p_yc_alpha*s_alpha_rad)^2+(p_yc_beta*s_beta_rad)^2+(p_yc_gamma*s_gamma_rad)^2+(p_yc_xf*x_error)^2+(p_yc_yf*y_error)^2+(p_yc_zf*z_error)^2];cart_errors[,s_zc_sq:=(p_zc_a*s_a)^2+(p_zc_b*s_b)^2+(p_zc_c*s_c)^2+(p_zc_alpha*s_alpha_rad)^2+(p_zc_beta*s_beta_rad)^2+(p_zc_gamma*s_gamma_rad)^2+(p_zc_xf*x_error)^2+(p_zc_yf*y_error)^2+(p_zc_zf*z_error)^2]
  all_frac_coords<-unique(rbind(atomic_coordinates[,.(Label,x_a,y_b,z_c)],expanded_coords),by="Label");all_cart_coords<-all_frac_coords[,`:=`(xc=a*x_a+b*y_b*cos_g+c*z_c*cos_b,yc=b*y_b*sin_g+c*z_c*(cos_a-cos_b*cos_g)/sin_g,zc=c*z_c*v/sin_g)][,.(Label,xc,yc,zc)];setkey(all_cart_coords,Label)
  error_subset<-cart_errors[,.(Label,s_xc_sq,s_yc_sq,s_zc_sq)];setkey(error_subset,Label);work_dt<-copy(bond_angles)
  work_dt[all_cart_coords,on=.(CentralAtom=Label),`:=`(xc1=i.xc,yc1=i.yc,zc1=i.zc)];work_dt[all_cart_coords,on=.(Neighbor1=Label),`:=`(xc2=i.xc,yc2=i.yc,zc2=i.zc)];work_dt[all_cart_coords,on=.(Neighbor2=Label),`:=`(xc3=i.xc,yc3=i.yc,zc3=i.zc)]
  work_dt[,Parent_C:=sub("_.*","",CentralAtom)];work_dt[,Parent_N1:=sub("_.*","",Neighbor1)];work_dt[,Parent_N2:=sub("_.*","",Neighbor2)]
  work_dt[error_subset,on=.(Parent_C=Label),`:=`(s_xc1_sq=i.s_xc_sq,s_yc1_sq=i.s_yc_sq,s_zc1_sq=i.s_zc_sq)];work_dt[error_subset,on=.(Parent_N1=Label),`:=`(s_xc2_sq=i.s_xc_sq,s_yc2_sq=i.s_yc_sq,s_zc2_sq=i.s_zc_sq)];work_dt[error_subset,on=.(Parent_N2=Label),`:=`(s_xc3_sq=i.s_xc_sq,s_yc3_sq=i.s_yc_sq,s_zc3_sq=i.s_zc_sq)]
  work_dt[,`:=`(a_vx=xc2-xc1,a_vy=yc2-yc1,a_vz=zc2-zc1,b_vx=xc3-xc1,b_vy=yc3-yc1,b_vz=zc3-zc1)];work_dt[,`:=`(mag_a=sqrt(a_vx^2+a_vy^2+a_vz^2),mag_b=sqrt(b_vx^2+b_vy^2+b_vz^2))];work_dt<-work_dt[mag_a>1e-9&mag_b>1e-9]
  work_dt[,C_val:=(a_vx*b_vx+a_vy*b_vy+a_vz*b_vz)/(mag_a*mag_b)];work_dt[,C_val:=pmin(pmax(C_val,-1.0),1.0)]
  work_dt[,`:=`(p_C_xc1=-(((b_vx/mag_b-C_val*a_vx/mag_a)/mag_a)+((a_vx/mag_a-C_val*b_vx/mag_b)/mag_b)),p_C_yc1=-(((b_vy/mag_b-C_val*a_vy/mag_a)/mag_a)+((a_vy/mag_a-C_val*b_vy/mag_b)/mag_b)),p_C_zc1=-(((b_vz/mag_b-C_val*a_vz/mag_a)/mag_a)+((a_vz/mag_a-C_val*b_vz/mag_b)/mag_b)),p_C_xc2=(b_vx/mag_b-C_val*a_vx/mag_a)/mag_a,p_C_yc2=(b_vy/mag_b-C_val*a_vy/mag_a)/mag_a,p_C_zc2=(b_vz/mag_b-C_val*a_vz/mag_a)/mag_a,p_C_xc3=(a_vx/mag_a-C_val*b_vx/mag_b)/mag_b,p_C_yc3=(a_vy/mag_a-C_val*b_vy/mag_b)/mag_b,p_C_zc3=(a_vz/mag_a-C_val*b_vz/mag_b)/mag_b)]
  work_dt[,s_C_sq:=(p_C_xc1^2*s_xc1_sq)+(p_C_yc1^2*s_yc1_sq)+(p_C_zc1^2*s_zc1_sq)+(p_C_xc2^2*s_xc2_sq)+(p_C_yc2^2*s_yc2_sq)+(p_C_zc2^2*s_zc2_sq)+(p_C_xc3^2*s_xc3_sq)+(p_C_yc3^2*s_yc3_sq)+(p_C_zc3^2*s_zc3_sq)];work_dt[C_val^2>=1.0,s_theta_sq:=0];work_dt[C_val^2<1.0,s_theta_sq:=s_C_sq/(1-C_val^2)]
  work_dt[,AngleError:=sqrt(pmax(0,s_theta_sq))*180/pi]
  return(merge(bond_angles,work_dt[,.(CentralAtom,Neighbor1,Neighbor2,AngleError)],by=c("CentralAtom","Neighbor1","Neighbor2"),all.x=TRUE))
}
